#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define MOD 1000000007

// ==========================================
// Generated by Bansal Universal Transpiler
// Domain: Trees
// Confidence: 61%
// ==========================================

struct LCA {
    int LOG; vector<int> depth; vector<vector<int>> up;
    LCA(int n, vector<vector<int>>& g, int root=0) {
        LOG = log2(n) + 1; depth.assign(n, 0); up.assign(n, vector<int>(LOG));
        dfs(root, root, g);
    }
    void dfs(int u, int p, vector<vector<int>>& g) {
        up[u][0] = p;
        for(int i=1; i<LOG; i++) up[u][i] = up[up[u][i-1]][i-1];
        for(int v : g[u]) if(v != p) { depth[v] = depth[u] + 1; dfs(v, u, g); }
    }
    int get(int u, int v) {
        if(depth[u] < depth[v]) swap(u, v);
        for(int i=LOG-1; i>=0; i--) if(depth[u]-(1<<i) >= depth[v]) u = up[u][i];
        if(u == v) return u;
        for(int i=LOG-1; i>=0; i--) if(up[u][i] != up[v][i]) { u = up[u][i]; v = up[v][i]; }
        return up[u][0];
    }
};



void solve() {

    // TODO: read input and call algorithm above

}

int main() {

    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int t = 1;
    // cin >> t;

    while(t--)
        solve();

    return 0;
}

