#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
#define MOD 1000000007

// ==========================================
// Generated by Pseudo2CPP
// Algorithm: Dijkstra
// Domain: Graphs
// Confidence: 99%
// Time: O((V + E) log V)
// Space: O(V + E)
// Use case: Single-source shortest path with non-negative weights.
// Warning: Do not use when negative edges exist.
// ==========================================

vector<ll> dijkstra(int n, vector<vector<pair<int,int>>>& g, int src) {
    vector<ll> dist(n, LLONG_MAX); dist[src] = 0;
    priority_queue<pair<ll,int>, vector<pair<ll,int>>, greater<>> pq;
    pq.push({0, src});
    while(!pq.empty()) {
        auto [d, u] = pq.top(); pq.pop();
        if(d > dist[u]) continue;
        for(auto& [v, w] : g[u]) {
            if(dist[v] > d + w) { dist[v] = d + w; pq.push({dist[v], v}); }
        }
    } return dist;
}


void solve() {
    int n, m, src;
    cin >> n >> m >> src;
    vector<vector<pair<int,int>>> g(n);
    for(int i = 0; i < m; i++) {
        int u, v, w;
        cin >> u >> v >> w;
        g[u].push_back({v, w});
    }
    vector<ll> dist = dijkstra(n, g, src);
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int t = 1;
    // cin >> t;

    while(t--) solve();
    return 0;
}
